# .pre-commit-config.yml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: main  # Ruff version tag from the repo’s Releases
    hooks:
      - id: ruff-check           # Linter
        args: [ --fix ]          # Optional: auto-fix lint issues
      - id: ruff-format          # Formatter
